default: &default
  adapter: mysql2
  database: caodoo
  username: caodoo
  password: caodoo
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  port: 3306

development:
  <<: *default
  host: localhost

test:
  <<: *default

production:
  <<: *default
  host: 192.168.1.187

