sms:
  username: vipswj
  password: Tch123456

security_code:

payment:
  expired: 30

sale:
  max_quantity: 10

contact:
  telephone: '400-6518-459'
  wechat: 'caodoo2015'

security_code:
  sms_template: "您的验证码是%{security_code}, 请在三分钟内输入"
  expired: 180

express_tracker:
  key: 'a64175d696824c568f654603e8d29870'

coupon:
  money: 10
  expired: 30