sms:
  username: vipswj
  password: Tch123456

security_code:

payment:
  expired: 30

sale:
  max_quantity: 10

contact:
  telephone: '400-6518-459'
  wechat: 'caodoo2015'

security_code:
  sms_template: "您的验证码是%{security_code}, 请在三分钟内输入"
  expired: 180

show_api:
  app_id: 3746
  sign: '51ff45c7ff4247f3834bd018a5e890e6'
