sms:
  username: vipswj
  password: Tch123456

security_code:
  disabled: true
  sms_template: "您的验证码是%{security_code}, 请在三分钟内输入"
  expired: 180

payment:
  expired: 30

sale:
  max_quantity: 10

contest:
  default_team_identifier: '85ab5238f634ae970da47c3863921e6c'
  level_exp: [0, 3, 5, 8]

contact:
  telephone: '400-6518-459'
  wechat: 'caodoo2015'

