mysql: &mysql
  adapter: mysql2
  database: caodoo
  username: caodoo
  pool: 25
  timeout: 5000
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  port: 3306

octopus: &octopus
  replicated: true
  environments:
    - production

  production:
    slave1:
      host: caodoodbslave.chhqxoiimdiw.rds.cn-north-1.amazonaws.com.cn
      password: Passw0rd
      <<: *mysql
