contest:
  default_team_identifier: '16c7cd1b9df7a2bc840ec02f7d8d4a7b'
  level_exp: [0, 9, 13, 16]

admin:
  username: 'caodoo-admin'
  password: 'Passw0rd'

security_code:
  disabled: true

customer_service:
    username: 'customer'
    password: 'customer'
